from building import *
import os

cwd = GetCurrentDir()

src = Glob('Core/Src/*.c')
src += Glob('Core/Startup/*.s')

CPPPATH = [cwd + '/Core/Inc']

group = DefineGroup('FSBL', src, depend = [''], CPPPATH = CPPPATH)

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
