import os
from building import *

cwd = GetCurrentDir()

# add the general drivers.
src = Glob('board.c')
src += Glob('startup_stm32n657xx_fsbl.s')
src += Glob('CubeMX_Config/FSBL/Src/stm32n6xx_hal_msp.c')
src += Glob('CubeMX_Config/FSBL/Src/system_stm32n6xx_fsbl.c')  
src += Glob('CubeMX_Config/Drivers/STM32N6xx_HAL_Driver/Src/*.c')  

path = [cwd]
path += [cwd + '/CubeMX_Config/FSBL/Inc']
path += [cwd + '/CubeMX_Config/Drivers/STM32N6xx_HAL_Driver/Inc']
path += [cwd + '/CubeMX_Config/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy']
path += [cwd + '/CubeMX_Config/Drivers/CMSIS/Include']
path += [cwd + '/CubeMX_Config/Drivers/CMSIS/Device/ST/STM32N6xx/Include']

# STM32N657xx
# You can select chips from the list above
CPPDEFINES = ['STM32N657xx']

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path)
list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
